config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  devise_for :admins
  resources :articles

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  #def initialize(user)      
   # user ||= User.new # guest user (not logged in)

    #if user.role :admin
     #   can :manage, :article
    #elsif user.role :author
    #    can :edit 
    
    #elsif
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
               length: { minimum: 5 }
	mount_uploader :image, ImageUploader
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.page(params[:page]).per(10)
  end

  def show
    @article = Article.find(params[:id])
    @random_articles =  Article.where.not(id: @article.id).order('RANDOM()').limit(2)
  end

  def new
    @article = Article.new    
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path    
  end


  private
  def article_params
    params.require(:article).permit(:title, :text, :image, :author_id, :views)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text.split('.').first %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
      			method: :delete,
      			data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= paginate @articles %>

<%= link_to 'Back', '/' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <%= image_tag @article.image %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<!--Show two random articles -->
<h3>Random articles</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @random_articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text.split('.').first %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>